apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: logging
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /run/promtail/positions.yaml

    clients:
      - url: http://loki:3100/loki/api/v1/push
        batch_wait: 1s
        batch_size: 102400

    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        pipeline_stages:
          - docker: {}
          - regex:
              expression: '\\[GIN\\]\\s+(?P<timestamp>\\d{4}/\\d{2}/\\d{2} - \\d{2}:\\d{2}:\\d{2})\\s+\\|\\s+(?P<status>\\d{3})\\s+\\|\\s+(?P<latency>[\\d\\.]+\\w+)\\s+\\|\\s+(?P<client_ip>[\\d\\.]+)\\s+\\|\\s+(?P<method>\\w+)\\s+(?P<path>.*)'
          - labels:
              status:
              method:
              path:
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            target_label: app
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_node_name
            target_label: instance
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - action: replace
            replacement: /var/log/pods/*$1/*.log
            separator: /
            source_labels:
              - __meta_kubernetes_pod_uid
              - __meta_kubernetes_pod_container_name
            target_label: __path__